### ISSUE TITLE
No sentenial-1 data downloaded post Flood_datetime.

### ISSUE THREAD

**Issue by acardaras-sanborn** [kleok/FLOODPY#59]
I have made the following modifications to my .cfg file and have noticed that the Sentinel_1_imagery directory 
only contains data prior(Aug 18 - Sept 15) to my specified Flood_datetime(Sept 16). Is this the expected behavior and is there any way to ensure imagery is downloaded on or after the specified Flood_datetime?

```
# B1. The datetime of flood event (Format is YYYYMMDDTHHMMSS)
Flood_datetime = 20200916T050000

# B2. Days before flood event for baseline stack construction
before_flood_days = 40

# B3. Days after flood event
after_flood_days = 3

# C2. AOI BBOX (WGS84)
LONMIN=-87.33
LATMIN=30.34
LONMAX=-87.26
LATMAX=30.40
```

**Comment by kleok** [comment]
Hello again :raised_hand_with_fingers_splayed: @acardaras-sanborn,
Thanks for using FloodPy, and providing valuable feedback :wink::
Floodpy checks if there are available images between ```Flood_datetime``` and ```Flood_datetime+after_flood_days```
 - if **Yes**, then the image closer to the ```Flood_datetime``` from this time span is downloaded.
 - If **No**, the image closer to the ```Flood_datetime```  between ```Flood_datetime - before_flood_days``` and ```Flood_datetime``` is downloaded.  
 
 You can ensure that you will always get an image after the specified ```Flood_datetime``` if you set for example ```after_flood_days = 24``` (due to revisit of Sentinel-1). However in this case, you can get images many days after the ```Flood_datetime``` which may not be useful for flood analysis.
I hope this help you :smile:
