### ISSUE TITLE
AssertionError: Houston we've got a problem. We encountered a problem in the coregistration procedure due to a small number of images before flood. 

### ISSUE THREAD

**Issue by JPPereira93** [kleok/FLOODPY#65]
Hello again! I'm running Floodpy for a new AOI however this error is showing:

![image](https://user-images.githubusercontent.com/90710707/227954414-d9f2d1d4-76d0-4d9e-895b-3f4915c824fc.png)

I have increased the number of before_flood_days to 100 and still i get this error. I didn't get this in an earlier Floodpy version

I'm running FLOODPYapp.py FLOODPYapp_template.cfg all at once because doing with --dostep i would get an error when pre processing Sentinel 1 data.

Any way to solve this? Thanks!

**Comment by kleok** [comment]
Hello again @JPPereira93 :smiley: 
In order to decrease flood map errors, after some experimentation I decided that the change detection analysis should be performed by using at least 3 pre-flood images. In your case, only 2 Sentinel-1 images exist before your flood event. There are no other Sentinel-1 images because Sentinel-1 started to deliver images from October 2014. In order to overcome this for your case you can comment the following line.
https://github.com/kleok/FLOODPY/blob/849ec0cc12bc3bcfa22249f11b775a0b801341fd/floodpy/Statistical_analysis/calc_t_scores.py#L103
If you require any further information, let me know :smile:

**Comment by JPPereira93** [comment]
Thank you kleok! Much appreciated, 😄
