### ISSUE TITLE
Issue in Preprocessing_S1_data.py

### ISSUE THREAD

**Issue by vishalshiv** [kleok/FLOODPY#66]
Hi Team,
I am running the FLOODPY for event happened in Solingen, Germany but getting the below error in Preprocessing_S1_data.py. 

File "C:\Users\Pmathur\Anaconda3\envs\floodpy\lib\site-packages\floodpy\Preprocessing_S1_data\Preprocessing_S1_data.py", line 528, in Run_Preprocessing
    Subset_AOI,

UnboundLocalError: local variable 'Subset_AOI' referenced before assignment

It might be happening because two adjacent GRD tile are getting used in pre-event tile but flood event has only one GRD tile as 2 and 3 tile in table below:
 | ERA5_tp_mm | baseline | S1_GRD | Datetime
1 | 23.0889534 | TRUE | E:\Vishal_2022\FloodEventResponse\SOLINGEN\Sentinel_1_imagery\S1A_IW_GRDH_1SDV_20210609T055025_20210609T055050_038259_0483CC_2C8D.zip | 6/9/2021 5:50
2 | 23.73645536 | TRUE | E:\Vishal_2022\FloodEventResponse\SOLINGEN\Sentinel_1_imagery\S1B_IW_GRDH_1SDV_20210615T054935_20210615T055000_027363_0344A0_DAC1.zip | 6/15/2021 5:49
3 | 23.73645536 | TRUE | E:\Vishal_2022\FloodEventResponse\SOLINGEN\Sentinel_1_imagery\S1B_IW_GRDH_1SDV_20210615T055000_20210615T055025_027363_0344A0_13F8.zip | 6/15/2021 5:50
4 | 22.57493026 | TRUE | E:\Vishal_2022\FloodEventResponse\SOLINGEN\Sentinel_1_imagery\S1A_IW_GRDH_1SDV_20210621T055025_20210621T055050_038434_048908_F67D.zip | 6/21/2021 5:50
5 | 37.8658546 | TRUE | E:\Vishal_2022\FloodEventResponse\SOLINGEN\Sentinel_1_imagery\S1B_IW_GRDH_1SDV_20210627T054935_20210627T055000_027538_03498A_B833.zip | 6/27/2021 5:49
6 | 37.8658546 | TRUE | E:\Vishal_2022\FloodEventResponse\SOLINGEN\Sentinel_1_imagery\S1B_IW_GRDH_1SDV_20210627T055000_20210627T055025_027538_03498A_86D9.zip | 6/27/2021 5:50
7 | 47.67774148 | TRUE | E:\Vishal_2022\FloodEventResponse\SOLINGEN\Sentinel_1_imagery\S1A_IW_GRDH_1SDV_20210703T055026_20210703T055051_038609_048E45_DD91.zip | 7/3/2021 5:50
8 | 71.55205072 | TRUE | E:\Vishal_2022\FloodEventResponse\SOLINGEN\Sentinel_1_imagery\S1B_IW_GRDH_1SDV_20210709T054936_20210709T055001_027713_034EA7_4B41.zip | 7/9/2021 5:49
9 | 71.60350636 | TRUE | E:\Vishal_2022\FloodEventResponse\SOLINGEN\Sentinel_1_imagery\S1B_IW_GRDH_1SDV_20210709T055001_20210709T055026_027713_034EA7_EA87.zip | 7/9/2021 5:50
10 | 164.908054 | FALSE | E:\Vishal_2022\FloodEventResponse\SOLINGEN\Sentinel_1_imagery\S1A_IW_GRDH_1SDV_20210715T055027_20210715T055052_038784_049389_5004.zip | 7/15/2021 5:50

**PARAMETERS USED:**
#A1. The name of your project withough special characters.
Projectname = 'Solingen'

#A2. The location that everything is going to be saved. Make sure
projectfolder = r'E:\Vishal_2022\FloodEventResponse\SOLINGEN'

#A3. The location of floodpy code
src_dir = r'C:\Users\Pmathur\FLOODPY-main\floodpy'

#A4. SNAP ORBIT DIRECTORY
snap_dir = r'C:\Users\Pmathur\.snap\auxdata\Orbits\Sentinel-1'

#A5. SNAP GPT full path
GPTBIN_PATH = r"C:\Program Files\snap\bin\gpt.exe"
Flood_datetime = '20210714T000000'#20200921T030000'

before_flood_days = 40

after_flood_days = 3

AOI_File = "None”
LONMIN=6.5
LATMIN=51.1
LONMAX=7.2
LATMAX=51.3

days_back = 12

accumulated_precipitation_threshold = 120

#E1. The number of Sentinel-1 relative orbit. The default
S1_type = 'GRD'
relOrbit = 'Auto'

#E3. The minimum mapping unit area in square meters
minimum_mapping_unit_area_m2=4000

#E4. Computing resources to employ
CPU=8
RAM='20G'

Please have a look and let me know how we can run it for the above parameters.
Thanks
Vishal

**Comment by kleok** [comment]
Hello @vishalshiv, 
Thanks for using Floodpy :smile: 
You are right, this issue was related to the number of  GRD tiles that are required for your AOI. I implemented the required functionalities and now preprocessing between two dates is supported  for any combinations of number of GRD tiles.
Let me know if this works for you too.

**Comment by kleok** [comment]
I am having a look at your case and I would like to provide some information that I believe can be helpful.
According to ERA5 precipitation, there was a big rain event.
![image](https://user-images.githubusercontent.com/7121726/232311785-79c03316-7cd4-4f7c-9b47-7f4ffe2f6389.png)
However according to the t-score image (changes of the Sentinel-1 backscatter), there are not evident/big backscatter drops (reddish tones). There are some regions close to the river network of your area which appear to be flooded (red color), but due to their small spatial size and small backscatter change I expect the Floodpy results to have lots of errors. My suggestion is to have a careful look only at the t-scores image which can help you better understand the flooding event. 
![image](https://user-images.githubusercontent.com/7121726/232312152-8f885ada-cb2e-4e54-84db-2085513d6bda.png)
I hope my interpretation helps :smiley:
